### ISSUE TITLE
git-crev: Reviewing individual Git commits.

### ISSUE THREAD

**Issue by rffrancon** [crev-dev/crev#2]
As I understand, Crev currently supports reviewing packages in their entirety only. Reviewing an entire package takes a long time. Which means that the number of people who can participate in the Crev WoT is small.

I would like to see Crev become common place and used routinely by a lot more people. This will have second order benefits.

With this in mind, I think that the minimal amount of work necessary to contribute to the WoT should be minimized. In my opinion, the smallest sensible atomic contribution is a review of a single commit.

Therefore, I think that it's sensible to create a git extension: `git crev ...` and a GitHub extension.

@dpc , or others: What are your thoughts on this issue? Has this been discussed before?

**Comment by kornelski** [comment]
crates-io ships packages, not commits. It doesn't require packages to have any repository at all, and even when packages declare they have a repository, it doesn't care if the code in the package is the same as code in the repository or not.

So while technically it'd be super easy to let crev sign info such as "I've reviewed commit 0fa1234f", it wouldn't be meaningful in evaluation of crates-io packages. Use of this information would require a lot of commit reviews to reconstruct the entire published package from the scraps. Note that if the lines you review aren't exactly the same as the lines shipped in the package, we can't trust them.

**Comment by dpc** [comment]
Initially `crev` was supposed to let people review particular files and distribute this along with the source code of each project. I was convinced that reviewing whole packages has more value with less work to implement it. But the code to support per-file review is still there and if successful I might get back to implementing this form of code review.

**Comment by rffrancon** [comment]
Thank you both for replying!

@kornelski I agree with you that `cargo-crev` shouldn't manage reviews for git commits. I think the Cargo implementation of Crev is heading down the correct path. What I'm proposing here is another implementation of Crev but for Git. That's why I've created this issue at `crev-dev/crev` instead of `crev-dev/cargo-crev`.

@dpc That's interesting. I might start playing around with a git extension (without blocking anyone else from working on it, of course). I think it will be possible to do some interesting things such as trusting all commits by a given author.

**Comment by dpc** [comment]
@rffrancon Where I work at (bitgo), we do utilize pgp signed commits in many advanced ways, so I am familiar with the subject. I think a system/idea like `crev` (basically pairing it with subjective WoT and a standardized data format) would fit that purpose well, and `crev` is explicitly flexible and open enough to accommodate it.

I personally barely have time to push core `crev` going forward, but I would be very happy to help you if you're interested in pursing it. If you want we can create a repo under ` crev-dev` org, and discuss some use cases etc, and any other stuff necessary to get this going.

**Comment by rffrancon** [comment]
@dpc I'm glad you agree that it's a reasonable direction to take. I think a repo under `crev-dev` makes sense. I would be happy to discuss use cases with you and make an attempt at an initial version.

As a first step I'm going to spend some time this Thursday re-familiarizing myself with the current code base. Looking forward!

**Comment by dpc** [comment]
@rffrancon I was looking into spliting `cargo-crev` into libraries and it made me think - do we have to do it? 

It seems to me that we could keep the libraries in `cargo-crev` repo for now, and you could git submodule that repo, and use

```
[dependencies]
crev_data = { path = "./lib/cargo-crev/cargo-data", version = "0.9" }
...
```


or something like that. You would be able to upgrade the libraries version at your own pace by bumping the submodule, and the fact that `cargo-crev` binary is also there is irrelevant.

Once things are more serious, we could formalize and actually split out the libs, but for now I'd like to postpone it, since it's has an overhead.

**Comment by dpc** [comment]
https://github.com/google/git-appraise - just to make sure you know about it @ffranr

**Comment by ffranr** [comment]
@dpc I think `git-appraise` makes the `git-crev` idea a bit obsolete. `git-appraise` looks like a great project. Thank you for pointing it out!
