### ISSUE TITLE
Restrict trust and reviews to a single language

### ISSUE THREAD

**Issue by LaurenceGA** [crev-dev/crev#6]
I've [started working on a Go implementation](https://github.com/LaurenceGA/go-crev/) and I see there's now an active [Julia implementation](https://github.com/non-Jedi/Crev.jl) from @non-jedi.

Following up from #4, we might want to think a bit more about CREV standardisation and interoperability.

Of course, reviews themselves won't really be shared between languages (Java + Kotlin I guess is an exception?). Things that would be shared would perhaps be identity and proof repositories.
One thing I think maybe shouldn't be shared is trust. I may trust someone's judgement of Rust code, but not of Go code, for example.

So what do you think of giving each proof a [language code](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) for the language(s) it pertains to? Maybe we can add scopes to trusts or something? Or maybe just a flag?

Some edge cases here could be cases where packages have multiple languages (C + Go, Kotlin + Java, Javascript + Typescript (do we care?), C + ...)

Maybe it's worth [versioning now?](https://github.com/crev-dev/cargo-crev/blob/85b61d92fb18c92fa8333164bfa8b6e0318ffc20/crev-data/src/proof/review/package.rs#L12). (Should this be a different issue?)

**Comment by kornelski** [comment]
One language code may be insufficient, because you may have different levels of trust for the same person, but different languages.

How about having a concept of a "trust domain". In addition to the default level of trust, you can specify level of trust per domain.

Tools will default to a certain domain, e.g. cargo-crev will default to "rust".

If trust is not specified for a given domain, the tool takes the default level instead.

**Comment by kornelski** [comment]
Alternatively, everyone could have multiple identities, one per language, and maintain web of trust for each language.

**Comment by LaurenceGA** [comment]
> One language code may be insufficient, because you may have different levels of trust for the same person, but different languages.

Agreed.

> How about having a concept of a "trust domain". The domain is an arbitrary identifier. In addition to the default level of trust, you can specify level of trust per domain.

I think that's a good idea. Is there benefit to letting the domain be an arbitrary identifier over a single language (which we can have multiple of)? We'd still need to agree on them somehow I think.

> Tools will default to a certain domain, e.g. cargo-crev will default to "rust".
>
>If trust is not specified for a given domain, the tool takes the default level instead.

:+1: 

> Alternatively, everyone could have multiple identities, one per language, and maintain web of trust for each language.

Possible. It would be less convenient for users and does pose some barrier to entry for each new language they may wish to use crev in.
There could be a problem though too if we implement more ID types ([PGP ID](https://github.com/crev-dev/cargo-crev/issues/58), [Github ID](https://github.com/LaurenceGA/go-crev/issues/9)). In these situations I think it's even more impractical to expect a user to maintain multiple identities.
Also from an implementation perspective having an explicit language code would help identifying whether to consider a proof or not. We'd probably still have users putting crev proofs in the same repo and we have to sort through them somehow.

Scoping trust essentially provides a built-in way to cleanly split a user's web of trust without expecting them to maintain multiple identities.

**Comment by dpc** [comment]
Anything I say is just my opinion, and ultimately I'd like the community evolve in whatever direction desired, so don't worry too much about it.

> Maybe it's worth versioning now?. (Should this be a different issue?)

The -1 version is there already and is supposed to mark the fact that I did the exact format is still an alpha. I wanted to have more people looking at these formats and writing a different implementation before commiting to anything. Proof parsers should ignore fields that they don't understand, so one can always extend the format without breaking other others. Incrementing the format version might never be needed, but just in case - it is there.

> One thing I think maybe shouldn't be shared is trust. I may trust someone's judgement of Rust code, but not of Go code, for example.

I personally think it's spliting hairs.

When I was muling about what fields to put in proofs I was trying to find a minimum essential data to make it all work, without bothering users with too much work. I really believe that every additional field is additonal burden, diluting users motivation and attention.

Special cases are also a be a burden for each implementation, tools, etc. leading to bugs and less tools being written and working. 

So I generally would advise delaying adding fields like this until there are enough people that need them, and enough data, use cases, etc. to design them well.

BTW. The "trust" field is supposed to be more about trust, than about rating skills/knowledge. It's hard to separate in practice, but it's important to recognize. In theory one could give "high: trust" someone that is releatively noobish, as long as they know that that person will do a responsible job and mark their reviews with "understanding: low" etc. This field is more about things like "this is an official account of respected company employee", "this is a security researcher", "core language developer" etc.

So in this example I'd say... if you trust someone doing Rust code reviews, don't you trust them to know that they are not a Go expert? If you don't ... maybe you should not be trusting them so much in the first place, and just lower your trust level altogether. 

And then language is not the only useful special case. What if someone is well known embedded developer, but you don't trust them reviewing type theory libraries, or machine learning ones. And so on.

So my general answer to all "in certain cases I want trust someone differently" is: just go with the lowest common denominator trust level.

**Comment by LaurenceGA** [comment]
> I wanted to have more people looking at these formats and writing a different implementation before commiting to anything

Fair enough. Makes sense to hold off then.

> BTW. The "trust" field is supposed to be more about trust, than about rating skills/knowledge.

I see. That would make this go against that idea.

> So I generally would advise delaying adding fields

:+1: I was mainly preempting this in anticipation of it simplifying implementation.

In light of that, I think we can close this. It can just be reopened if implementation prompts this to come up again.

Thanks for the response :grin: 

Let's just build the bridge when we come to it.
